Repository stefanradouane/plantswap, pull requests merged in 2023-06, with the labels that each got.

#13 Feature#3 resultaten
  plantswap/components/Results/Results.js
  plantswap/components/Results/results.module.scss
  plantswap/src/app/[lang]/swap/page.js
Labels: enhancement

#14 ADD, Plant form component :sparkles:
  plantswap/components/Form/Form.js
  plantswap/components/Form/form.module.scss
  plantswap/package-lock.json
  plantswap/package.json
  plantswap/src/app/[lang]/globals.css
  plantswap/src/app/[lang]/planten/[id]/page.js
Labels: enhancement, User Story, Sprint 3, Must Have

#22 ADD, Created Accordion component, and added filter out green functionality :sparkles:
  plantswap/components/Accordion/Accordion.js
  plantswap/components/Accordion/accordion.module.scss
  plantswap/components/Detailpage/Detailpage.js
  plantswap/components/Detailpage/detailpage.module.scss
  plantswap/components/DetailpageArticle/DetailpageArticle.js
  plantswap/components/DetailpageArticle/detailpagearticle.module.scss
  plantswap/components/DetailpageHeader/DetailpageHeader.js
  plantswap/components/DetailpageHeader/detailpageheader.module.scss
  plantswap/components/DetailpageHeaderImage/DetailpageHeaderImage.js
  plantswap/components/DetailpageHeaderImage/detailpageheaderimage.module.scss
  plantswap/components/Title/title.module.scss
  plantswap/src/app/[lang]/globals.css
Labels: Sprint 3, Should Have
